### ISSUE TITLE
error when using Vite with @antv/l7

### ISSUE THREAD

**Issue by Jungzl** [KyleAMathews/element-resize-event#36] opened 2021-05-18 02:20 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `element-resize-event@3.0.3` for the project I'm working on.

I'm using Vite with @antv/l7 which has your project as one of the dependcies. 
![image](https://user-images.githubusercontent.com/35426360/118580049-bfd65d00-b7c1-11eb-8c1a-abe1cfbbcfa4.png)

Since Vite prebundled all modules with esbuild when developing, it tells me that 
![image](https://user-images.githubusercontent.com/35426360/118579855-6bcb7880-b7c1-11eb-86a0-debc890fb678.png)

Maybe the function name `exports ` is confused with module.exports here.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/element-resize-event/index.js b/node_modules/element-resize-event/index.js
index fb1e2a3..d26e41a 100644
--- a/node_modules/element-resize-event/index.js
+++ b/node_modules/element-resize-event/index.js
@@ -14,7 +14,7 @@ function resizeListener(e) {
   })
 }
 
-var exports = function exports(element, fn) {
+var _exports = function _exports(element, fn) {
   var window = this
   var document = window.document
   var isIE
@@ -64,7 +64,7 @@ var exports = function exports(element, fn) {
   element.__resizeListeners__.push(fn)
 }
 
-module.exports = typeof window === 'undefined' ? exports : exports.bind(window)
+module.exports = typeof window === 'undefined' ? _exports : _exports.bind(window)
 
 module.exports.unbind = function (element, fn) {
   var attachEvent = document.attachEvent
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by nobleach** [comment] 2021-05-29 15:05
This is great find, this is also affecting Rsuite. I filed an issue on their GitHub, but this looks to be the cause of that issue: https://github.com/rsuite/rsuite/issues/1705

**Comment by KyleAMathews** [comment] 2021-05-30 08:36
Fixed in https://github.com/KyleAMathews/element-resize-event/pull/37

**Closed as completed by KyleAMathews** 2021-05-30 08:36 UTC
